### ISSUE TITLE
Compiled errors  of  "make GENERIC"

### ISSUE THREAD

**Issue by xuhenry** [spatialfruitsalad/pomelo#3]
Dear all,
   There are some errors when I compiled the code using"make GENERIC".
   the version of lua is 5.3. And the operate system is Ubuntu 18.04
The errors as follows : 

clang++ -Wall -Wextra -O3 -std=c++1y  obj/main.o obj/voro.o obj/fileloader.o obj/pointpattern.o -o bin/pomelo -llua5.3 -I/usr/include/lua5.3 -DUSELUA 
/usr/bin/ld: cannot find -llua5.3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:39: recipe for target 'LINK' failed
make: *** [LINK] Error 1

Thanks a lot!
Best regards
Henry

**Comment by spatialfruitsalad** [comment]
Hi Henry,

It looks like your system cannot find the lua library. Please make sure you have installed the respective version through your packet management (in this case 5.3). Note that at least lua 5.2 is required. 
Often also the developer library is required, named liblua-devel or similar. 
Library names can differ based on the linux distribution. Please mane sure to adapt the Makefile in case of other library names.

Best regards,
Simon

**Comment by xuhenry** [comment]
@spatialfruitsalad 
Hi Simon, 
    The problem has been solved. Thanks a lot!
Best regards,
Henry
